services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data #data already persists 12.12 complete
    command: redis-server --requirepass redis_pass-123 --appendonly yes
    restart: unless-stopped

  debug-helper:
    image: busybox

  server:
    image: hello-back-dev
    container_name: app-backend
    ports:
      - "3005:3000"
    environment:
      REDIS_URL: redis://:redis_pass-123@redis:6379
      MONGO_URL: mongodb://root:example@mongo:27017/the_database?authSource=admin
    volumes:
      - .:/usr/src/app

volumes:
  mongo_data:
  redis-data:
    driver: local
