services:
  app:
    image: frontend-todo-img
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 5173:5173
    container_name: frontend-todo-container
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-full
    depends_on:
      - app # wait for the frontend container to be started
